version: "3.9"

services:
  db:
    image: postgres
    restart: always
    container_name: ${PG_CONTAINER}
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
